Hope is a drug
Smiles are a vice

Games are best when nothing is at stake, but pride

Laughs are an infectious disease
There is no immunization against giggles

farts we could use a cure for
we can make the same noises with our armpits

tickles are a form of torture the Geneva convention
has yet to recognize

skipping should be an Olympic sport
but so should sledding
we would take the gold for, for group sledding at least

sass is evil
pillow fights are criminal
snowballs fights are war crimes

but without all these vices
life would be empty, void
so revel in your worst nature
snuggle deeply
huh warmly
and bow to loud applause
